# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(verbose_name='Date')),
                ('is_draft', models.BooleanField(default=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='WikiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(verbose_name='Date')),
                ('content', models.TextField()),
            ],
        ),
    ]
