# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_charts'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='type',
            field=models.CharField(choices=[('line', 'line'), ('bar', 'bar')], default='line', max_length=50),
        ),
    ]
