# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161020_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hid',
            field=models.TextField(default=True, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
