# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_hid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hid',
            field=models.TextField(max_length=10),
        ),
    ]
