# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_charts_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charts',
            options={'verbose_name_plural': 'Charts'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='wikiinform',
            options={'verbose_name_plural': 'Wiki'},
        ),
    ]
