# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161027_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hid',
        ),
    ]
