# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
